# Generated by Django 3.2.16 on 2023-10-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_journals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='Articles',
        ),
    ]
