# Generated by Django 3.2.16 on 2023-10-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_journals', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='title',
            new_name='headline',
        ),
    ]
